2021-03-06 22:48:30,195 ERROR: Exception on /user/Boyo94 [GET] [in /home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/projectsUbuntu/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts.items, form=form, prev_url=prev_url, next_url=next_url)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/projectsUbuntu/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/projectsUbuntu/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/mnt/c/projectsUbuntu/microblog/app/templates/base.html", line 33, in block "content"
    {% block app_content %}{% endblock %}
  File "/mnt/c/projectsUbuntu/microblog/app/templates/user.html", line 8, in block "app_content"
    <h1>{{ _('User') }}: {{ user.username }}</h1>
jinja2.exceptions.UndefinedError: '_' is undefined
2021-03-06 22:48:57,404 INFO: Microblog startup [in /mnt/c/projectsUbuntu/microblog/app/__init__.py:48]
2021-03-06 22:49:01,546 ERROR: Exception on /user/Boyo94 [GET] [in /home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/projectsUbuntu/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts.items, form=form, prev_url=prev_url, next_url=next_url)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/mnt/c/projectsUbuntu/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/mnt/c/projectsUbuntu/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/mohamed/miniconda3/envs/mypyenv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/mnt/c/projectsUbuntu/microblog/app/templates/base.html", line 33, in block "content"
    {% block app_content %}{% endblock %}
  File "/mnt/c/projectsUbuntu/microblog/app/templates/user.html", line 8, in block "app_content"
    <h1>{{ _('user') }}: {{ user.username }}</h1>
jinja2.exceptions.UndefinedError: '_' is undefined
2021-03-06 22:57:59,410 INFO: Microblog startup [in /mnt/c/projectsUbuntu/microblog/app/__init__.py:48]
2021-03-06 22:58:22,852 INFO: Microblog startup [in /mnt/c/projectsUbuntu/microblog/app/__init__.py:48]
